//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::notes::Entity as Notes;
pub use super::orders::Entity as Orders;
pub use super::posts::Entity as Posts;
pub use super::users::Entity as Users;
